name: Deploy Website

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

    - name: Upload files to server
      run: |
        scp -r ./ developer@192.168.4.142:/var/www/html/
